// GENERATED FILE — do not edit by hand.
// Regenerate with: node scripts/generate-code-snippets.mjs
// Each entry is the real, verbatim source of the function(s) that
// chapter's scene actually calls, extracted from src/lib/local-geometry.ts.

import type { QueryType } from "@/types/geometry";

export type CodeSnippet = {
  sourceLabel: string;
  code: string;
};

export const CODE_SNIPPETS: Partial<Record<QueryType, CodeSnippet>> = {
  "angles": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localAngle(rayB: Vec3): AngleResponse {\n  let angleDeg = Math.atan2(rayB.y, rayB.x) * (180 / Math.PI);\n  if (angleDeg < 0) angleDeg += 360;\n\n  const classification: AngleClassification =\n    Math.abs(angleDeg - 90) < ANGLE_EPSILON_DEG ? \"right\" :\n    Math.abs(angleDeg - 180) < ANGLE_EPSILON_DEG ? \"straight\" :\n    angleDeg < 90 ? \"acute\" :\n    angleDeg < 180 ? \"obtuse\" : \"reflex\";\n\n  const complementDeg = angleDeg <= 90 ? 90 - angleDeg : null;\n  const supplementDeg = angleDeg <= 180 ? 180 - angleDeg : null;\n\n  return { angleDeg, classification, complementDeg, supplementDeg };\n}"
  },
  "pythagorean-theorem": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localPythagorean(legAPoint: Vec3, legBPoint: Vec3): PythagoreanResponse {\n  const legA = Math.max(Math.hypot(legAPoint.x, legAPoint.y), EPSILON);\n  const legB = Math.max(Math.hypot(legBPoint.x, legBPoint.y), EPSILON);\n  const hypotenuse = Math.sqrt(legA * legA + legB * legB);\n  const triangleType = Math.abs(legA - legB) < 1e-6 ? \"isosceles\" : \"scalene\";\n  return { legA, legB, hypotenuse, triangleType };\n}"
  },
  "right-triangle-trig": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localRightTriangleTrig(anglePoint: Vec3): RightTriangleTrigResponse {\n  const rawDeg = Math.atan2(Math.abs(anglePoint.y), Math.max(anglePoint.x, EPSILON)) * (180 / Math.PI);\n  const angleDeg = Math.max(1, Math.min(89, rawDeg));\n  const angleRad = angleDeg * (Math.PI / 180);\n  const hypotenuse = RIGHT_TRIANGLE_TRIG_HYPOTENUSE;\n  const sinValue = Math.sin(angleRad);\n  const cosValue = Math.cos(angleRad);\n  const tanValue = Math.tan(angleRad);\n  return {\n    angleDeg,\n    sin: sinValue,\n    cos: cosValue,\n    tan: tanValue,\n    opposite: hypotenuse * sinValue,\n    adjacent: hypotenuse * cosValue,\n    hypotenuse,\n  };\n}"
  },
  "circle-measures": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localCircleMeasures(radiusPoint: Vec3, anglePoint: Vec3): CircleMeasuresResponse {\n  const radius = Math.max(Math.hypot(radiusPoint.x, radiusPoint.y), EPSILON);\n  let centralAngleDeg = Math.atan2(anglePoint.y, anglePoint.x) * (180 / Math.PI);\n  if (centralAngleDeg <= 0) centralAngleDeg += 360;\n  const centralAngleRad = centralAngleDeg * (Math.PI / 180);\n  return {\n    radius,\n    circumference: 2 * Math.PI * radius,\n    area: Math.PI * radius * radius,\n    centralAngleDeg,\n    arcLength: radius * centralAngleRad,\n    sectorArea: 0.5 * radius * radius * centralAngleRad,\n  };\n}"
  },
  "regular-polygon": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function regularPolygonVertex(index: number, sides: number, circumradius: number): Vec3 {\n  const angle = (2 * Math.PI * index) / sides;\n  return { x: circumradius * Math.cos(angle), y: circumradius * Math.sin(angle), z: 0 };\n}\n\nexport function localRegularPolygon(sidesPoint: Vec3, radiusPoint: Vec3): RegularPolygonResponse {\n  const rawSides = Math.max(Math.hypot(sidesPoint.x, sidesPoint.y), REGULAR_POLYGON_MIN_SIDES);\n  const sides = Math.max(REGULAR_POLYGON_MIN_SIDES, Math.min(REGULAR_POLYGON_MAX_SIDES, Math.round(rawSides)));\n  const circumradius = Math.max(Math.hypot(radiusPoint.x, radiusPoint.y), EPSILON);\n  const perimeter = sides * 2 * circumradius * Math.sin(Math.PI / sides);\n  const area = 0.5 * sides * circumradius * circumradius * Math.sin((2 * Math.PI) / sides);\n  const interiorAngleDeg = ((sides - 2) * 180) / sides;\n  return { sides, circumradius, area, perimeter, interiorAngleDeg };\n}"
  },
  "transformations": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function transformTrianglePoint(\n  point: Vec3,\n  translation: { x: number; y: number },\n\nexport function localTransformations(translationPoint: Vec3, handlePoint: Vec3): TransformationsResponse {\n  const translation = { x: translationPoint.x, y: translationPoint.y };\n  const scale = Math.max(Math.hypot(handlePoint.x, handlePoint.y) / TRANSFORM_HANDLE_REFERENCE_RADIUS, EPSILON);\n  const rotationRad = Math.atan2(handlePoint.y, handlePoint.x);\n\n  const [base0, base1, base2] = TRANSFORM_BASE_TRIANGLE;\n  const after0 = transformTrianglePoint(base0, translation, rotationRad, scale);\n  const after1 = transformTrianglePoint(base1, translation, rotationRad, scale);\n  const after2 = transformTrianglePoint(base2, translation, rotationRad, scale);\n\n  return {\n    translationX: translation.x,\n    translationY: translation.y,\n    rotationDeg: rotationRad * (180 / Math.PI),\n    scale,\n    sampleAngleBeforeDeg: angleAtVertexDeg(base1, base0, base2),\n    sampleAngleAfterDeg: angleAtVertexDeg(after1, after0, after2),\n  };\n}"
  },
  "solids-3d": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localSolid(solidType: SolidType, dimA: number, dimB: number, dimC: number): SolidsResponse {\n  const a = clampDim(dimA);\n  const b = clampDim(dimB);\n  const c = clampDim(dimC);\n\n  switch (solidType) {\n    case \"cube\":\n      return { solidType, dimA: a, dimB: 0, dimC: 0, volume: a ** 3, surfaceArea: 6 * a * a, slantHeight: null };\n    case \"box\":\n      return {\n        solidType,\n        dimA: a,\n        dimB: b,\n        dimC: c,\n        volume: a * b * c,\n        surfaceArea: 2 * (a * b + a * c + b * c),\n        slantHeight: null,\n      };\n    case \"cylinder\":\n      return {\n        solidType,\n        dimA: a,\n        dimB: b,\n        dimC: 0,\n        volume: Math.PI * a * a * b,\n        surfaceArea: 2 * Math.PI * a * a + 2 * Math.PI * a * b,\n        slantHeight: null,\n      };\n    case \"cone\": {\n      const slantHeight = Math.hypot(a, b);\n      return {\n        solidType,\n        dimA: a,\n        dimB: b,\n        dimC: 0,\n        volume: (Math.PI * a * a * b) / 3,\n        surfaceArea: Math.PI * a * a + Math.PI * a * slantHeight,\n        slantHeight,\n      };\n    }\n    case \"sphere\":\n      return {\n        solidType,\n        dimA: a,\n        dimB: 0,\n        dimC: 0,\n        volume: (4 / 3) * Math.PI * a ** 3,\n        surfaceArea: 4 * Math.PI * a * a,\n        slantHeight: null,\n      };\n    case \"pyramid\": {\n      const slantHeight = Math.hypot(b, a / 2);\n      return {\n        solidType,\n        dimA: a,\n        dimB: b,\n        dimC: 0,\n        volume: (a * a * b) / 3,\n        surfaceArea: a * a + 2 * a * slantHeight,\n        slantHeight,\n      };\n    }\n  }\n}"
  },
  "cross-sections": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function classifyConic(coneHalfAngleDeg: number, planeTiltDeg: number): { conicType: ConicType; discriminant: number } {\n  const alpha = coneHalfAngleDeg * (Math.PI / 180);\n  const m = Math.tan(planeTiltDeg * (Math.PI / 180));\n  const discriminant = 4 * (Math.tan(alpha) * Math.tan(alpha) * m * m - 1);\n  const conicType: ConicType =\n    Math.abs(discriminant) < 1e-6 ? \"parabola\" : discriminant < 0 ? (Math.abs(planeTiltDeg) < 1e-6 ? \"circle\" : \"ellipse\") : \"hyperbola\";\n  return { conicType, discriminant };\n}\n\nexport function localCrossSection(coneHalfAngleDeg: number, planeTiltPoint: Vec3, offsetPoint: Vec3): CrossSectionResponse {\n  const planeTiltDeg = Math.max(-89, Math.min(89, Math.atan2(planeTiltPoint.y, Math.max(planeTiltPoint.x, EPSILON)) * (180 / Math.PI)));\n  const planeOffset = Math.max(0.4, Math.hypot(offsetPoint.x, offsetPoint.y));\n  const { conicType, discriminant } = classifyConic(coneHalfAngleDeg, planeTiltDeg);\n  return { coneHalfAngleDeg, planeTiltDeg, planeOffset, conicType, discriminant };\n}"
  },
  "nets": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localNet(foldPoint: Vec3): NetResponse {\n  const foldFraction = Math.max(0, Math.min(1, foldPoint.x));\n  return { side: NET_CUBE_SIDE, foldFraction, isFlat: foldFraction < 1e-6, isFolded: foldFraction > 1 - 1e-6 };\n}\n\n// Folds every face of the cube net to 3D at fold fraction t in [0, 1];\n// t=0 reproduces the flat net (z=0 everywhere), t=1 is the closed cube.\nexport function foldCubeNet(s: number, t: number): Record<\"base\" | \"north\" | \"south\" | \"east\" | \"west\" | \"top\", Vec3[]> {\n  const h = s / 2;\n  const phi = t * (Math.PI / 2);\n  const base: Vec3[] = [[-h, -h], [h, -h], [h, h], [-h, h]].map(([x, y]) => ({ x, y, z: 0 }));\n\n  // North/South fold around the x-axis-parallel hinge at y = ±h; the\n  // \"d\" coordinate is the flat distance from that hinge (0..s).\n  const foldNS = (yFlat: number, sign: 1 | -1): { y: number; z: number } => {\n    const d = sign * (yFlat - sign * h);\n    const { d: dFolded, z } = rotateLift(d, phi);\n    return { y: sign * h + sign * dFolded, z };\n  };\n  const north: Vec3[] = [[-h, h], [h, h], [h, h + s], [-h, h + s]].map(([x, y]) => {\n    const { y: yF, z } = foldNS(y, 1);\n    return { x, y: yF, z };\n  });\n  const south: Vec3[] = [[-h, -h], [h, -h], [h, -h - s], [-h, -h - s]].map(([x, y]) => {\n    const { y: yF, z } = foldNS(y, -1);\n    return { x, y: yF, z };\n  });\n\n  // East/West fold around the y-axis-parallel hinge at x = ±h.\n  const foldEW = (xFlat: number, sign: 1 | -1): { x: number; z: number } => {\n    const d = sign * (xFlat - sign * h);\n    const { d: dFolded, z } = rotateLift(d, phi);\n    return { x: sign * h + sign * dFolded, z };\n  };\n  const east: Vec3[] = [[h, -h], [h, h], [h + s, h], [h + s, -h]].map(([x, y]) => {\n    const { x: xF, z } = foldEW(x, 1);\n    return { x: xF, y, z };\n  });\n  const west: Vec3[] = [[-h, -h], [-h, h], [-h - s, h], [-h - s, -h]].map(([x, y]) => {\n    const { x: xF, z } = foldEW(x, -1);\n    return { x: xF, y, z };\n  });\n\n  // Top is hinged to North's own outer edge (North's d = s). Compose\n  // North's rotation (its current d-direction and normal) with Top's\n  // own fold fraction around that already-rotated hinge.\n  const northOuter = rotateLift(s, phi); // North's outer-edge d,z\n  const northHingeY = h + northOuter.d;\n  const northHingeZ = northOuter.z;\n  const dDir = { y: Math.cos(phi), z: Math.sin(phi) }; // North's own extension direction\n  const normalDir = { y: -Math.sin(phi), z: Math.cos(phi) }; // perpendicular, the fold-toward direction\n  const top: Vec3[] = [[-h, h + s], [h, h + s], [h, h + 2 * s], [-h, h + 2 * s]].map(([x, yFlat]) => {\n    const e = yFlat - (h + s); // distance beyond North's outer edge, 0..s\n    const y = northHingeY + e * (Math.cos(phi) * dDir.y + Math.sin(phi) * normalDir.y);\n    const z = northHingeZ + e * (Math.cos(phi) * dDir.z + Math.sin(phi) * normalDir.z);\n    return { x, y, z };\n  });\n\n  return { base, north, south, east, west, top };\n}"
  },
  "project-point-to-plane": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localProjectPointToPlane(input: ProjectPointToPlaneRequest): ProjectPointToPlaneResponse {\n  const magnitude = length(input.plane.normal);\n  if (magnitude < EPSILON) throw new Error(\"Plane normal cannot be zero\");\n  const normal = scale(input.plane.normal, 1 / magnitude);\n  const signedDistance = dot(sub(input.point, input.plane.point), normal);\n  return {\n    projectedPoint: sub(input.point, scale(normal, signedDistance)),\n    distance: Math.abs(signedDistance),\n  };\n}"
  },
  "intersect-ray-plane": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localIntersectRayPlane(input: IntersectRayPlaneRequest): IntersectRayPlaneResponse {\n  const denominator = dot(input.ray.dir, input.plane.normal);\n  if (Math.abs(denominator) < EPSILON) return { hit: false, point: input.ray.origin, t: 0 };\n  const t = dot(sub(input.plane.point, input.ray.origin), input.plane.normal) / denominator;\n  if (t < 0) return { hit: false, point: input.ray.origin, t };\n  return { hit: true, point: add(input.ray.origin, scale(input.ray.dir, t)), t };\n}"
  },
  "closest-point-segment": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localClosestPointSegment(input: ClosestPointSegmentRequest): ClosestPointSegmentResponse {\n  const ab = sub(input.segment.b, input.segment.a);\n  const lengthSquared = dot(ab, ab);\n  const t = lengthSquared < EPSILON ? 0 : clamp(dot(sub(input.point, input.segment.a), ab) / lengthSquared);\n  const point = add(input.segment.a, scale(ab, t));\n  return { point, distance: length(sub(input.point, point)) };\n}"
  },
  "segment-segment": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localSegmentSegment(input: SegmentSegmentRequest): SegmentSegmentResponse {\n  const u = sub(input.a2, input.a1);\n  const v = sub(input.b2, input.b1);\n  const w = sub(input.a1, input.b1);\n  const a = dot(u, u);\n  const b = dot(u, v);\n  const c = dot(v, v);\n  const d = dot(u, w);\n  const e = dot(v, w);\n  const denominator = a * c - b * b;\n  let sN = denominator;\n  let tN = denominator;\n  let sD = denominator;\n  let tD = denominator;\n\n  if (a < EPSILON && c < EPSILON) {\n    return { pointA: input.a1, pointB: input.b1, distance: length(sub(input.a1, input.b1)) };\n  }\n  if (a < EPSILON) {\n    sN = 0; sD = 1; tN = e; tD = c;\n  } else if (c < EPSILON) {\n    tN = 0; tD = 1; sN = -d; sD = a;\n  } else {\n    if (denominator < EPSILON) {\n      sN = 0; sD = 1; tN = e; tD = c;\n    } else {\n      sN = b * e - c * d;\n      tN = a * e - b * d;\n      if (sN < 0) { sN = 0; tN = e; tD = c; }\n      else if (sN > sD) { sN = sD; tN = e + b; tD = c; }\n    }\n    if (tN < 0) {\n      tN = 0;\n      sN = clamp(-d / a) * sD;\n    } else if (tN > tD) {\n      tN = tD;\n      sN = clamp((b - d) / a) * sD;\n    }\n  }\n\n  const s = Math.abs(sN) < EPSILON ? 0 : sN / sD;\n  const t = Math.abs(tN) < EPSILON ? 0 : tN / tD;\n  const pointA = add(input.a1, scale(u, s));\n  const pointB = add(input.b1, scale(v, t));\n  return { pointA, pointB, distance: length(sub(pointA, pointB)) };\n}"
  },
  "intersect-ray-aabb": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localIntersectRayAABB(input: IntersectRayAABBRequest): IntersectRayAABBResponse {\n  let tMin = 0;\n  let tMax = Number.POSITIVE_INFINITY;\n  for (const axis of [\"x\", \"y\", \"z\"] as const) {\n    const origin = input.ray.origin[axis];\n    const direction = input.ray.dir[axis];\n    const min = input.aabb.min[axis];\n    const max = input.aabb.max[axis];\n    if (Math.abs(direction) < EPSILON) {\n      if (origin < min || origin > max) return { hit: false, tMin: 0, tMax: 0, point: input.ray.origin };\n      continue;\n    }\n    let near = (min - origin) / direction;\n    let far = (max - origin) / direction;\n    if (near > far) [near, far] = [far, near];\n    tMin = Math.max(tMin, near);\n    tMax = Math.min(tMax, far);\n    if (tMin > tMax) return { hit: false, tMin, tMax, point: input.ray.origin };\n  }\n  return { hit: tMax >= 0, tMin, tMax, point: add(input.ray.origin, scale(input.ray.dir, tMin)) };\n}"
  },
  "closest-point-aabb": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localClosestPointAABB(input: ClosestPointAABBRequest): ClosestPointAABBResponse {\n  const point = {\n    x: clamp(input.point.x, input.aabb.min.x, input.aabb.max.x),\n    y: clamp(input.point.y, input.aabb.min.y, input.aabb.max.y),\n    z: clamp(input.point.z, input.aabb.min.z, input.aabb.max.z),\n  };\n  return { point, distance: length(sub(input.point, point)) };\n}"
  },
  "cartesian-transform": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function bilinearPoint(u: number, v: number, corners: CartesianTransformCorners): Vec3 {\n  const w00 = (1 - u) * (1 - v);\n  const w10 = u * (1 - v);\n  const w01 = (1 - u) * v;\n  const w11 = u * v;\n  return {\n    x: w00 * corners.p00.x + w10 * corners.p10.x + w01 * corners.p01.x + w11 * corners.p11.x,\n    y: w00 * corners.p00.y + w10 * corners.p10.y + w01 * corners.p01.y + w11 * corners.p11.y,\n    z: 0,\n  };\n}\n\nexport function localCartesianTransform(corners: CartesianTransformCorners): CartesianTransformResponse {\n  const currentPolygon = FISH_OUTLINE.map(([u, v]) => bilinearPoint(u, v, corners));\n  const referencePolygon = FISH_OUTLINE.map(([u, v]) => bilinearPoint(u, v, DEFAULT_TRANSFORM_CORNERS));\n\n  const currentArea = polygonArea(currentPolygon);\n  const referenceArea = polygonArea(referencePolygon);\n  const currentAspect = boundingAspect(currentPolygon);\n  const referenceAspect = boundingAspect(referencePolygon);\n\n  return {\n    currentArea,\n    referenceArea,\n    areaRatio: referenceArea < EPSILON ? 0 : currentArea / referenceArea,\n    elongation: referenceAspect < EPSILON ? 0 : currentAspect / referenceAspect,\n  };\n}"
  },
  "log-spiral-growth": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function logSpiralPoint(theta: number, a: number, b: number): Vec3 {\n  const r = a * Math.exp(b * theta);\n  return { x: r * Math.cos(theta), y: r * Math.sin(theta), z: 0 };\n}\n\nexport function localLogSpiral(input: { start: Vec3; turn: Vec3 }): LogSpiralResponse {\n  const a = Math.max(Math.hypot(input.start.x, input.start.y), EPSILON);\n  const rTurn = Math.max(Math.hypot(input.turn.x, input.turn.y), EPSILON);\n  const growthRatio = rTurn / a;\n  const b = Math.log(growthRatio) / (2 * Math.PI);\n  const pitchAngleDeg = Math.acos(Math.abs(b) / Math.sqrt(1 + b * b)) * (180 / Math.PI);\n  return { a, b, growthRatio, pitchAngleDeg };\n}"
  },
  "cell-packing": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "// The Voronoi cell of `site`: the region closer to it than to any site in\n// `others`, found by intersecting the perpendicular-bisector half-planes,\n// clipped to a bounding box so the diagram stays finite.\nexport function voronoiCell(site: Vec3, others: Vec3[]): Vec3[] {\n  let polygon: Vec3[] = [\n    { x: CELL_BOUNDS.minX, y: CELL_BOUNDS.minY, z: 0 },\n    { x: CELL_BOUNDS.maxX, y: CELL_BOUNDS.minY, z: 0 },\n    { x: CELL_BOUNDS.maxX, y: CELL_BOUNDS.maxY, z: 0 },\n    { x: CELL_BOUNDS.minX, y: CELL_BOUNDS.maxY, z: 0 },\n  ];\n  for (const other of others) {\n    const normal = { x: other.x - site.x, y: other.y - site.y };\n    const c = (other.x * other.x + other.y * other.y - (site.x * site.x + site.y * site.y)) / 2;\n    polygon = clipPolygonHalfPlane(polygon, normal, c);\n    if (polygon.length === 0) break;\n  }\n  return polygon;\n}\n\nexport function localCellPacking(center: Vec3): CellPackingResponse {\n  const cell = voronoiCell(center, CELL_RING_SITES);\n  const area = polygonArea(cell);\n  const perimeter = polygonPerimeter(cell);\n  return {\n    area,\n    perimeter,\n    isoperimetricQuotient: perimeter < EPSILON ? 0 : (4 * Math.PI * area) / (perimeter * perimeter),\n    sides: countPolygonSides(cell),\n  };\n}"
  },
  "helical-shell-growth": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function helicalShellPoint(theta: number, a: number, b: number, c: number): Vec3 {\n  const r = a * Math.exp(b * theta);\n  return { x: r * Math.cos(theta), y: r * Math.sin(theta), z: c * theta };\n}\n\nexport function localHelicalShell(input: { start: Vec3; turn: Vec3 }): HelicalShellResponse {\n  const a = Math.max(Math.hypot(input.start.x, input.start.y), EPSILON);\n  const rTurn = Math.max(Math.hypot(input.turn.x, input.turn.y), EPSILON);\n  const growthRatio = rTurn / a;\n  const b = Math.log(growthRatio) / (2 * Math.PI);\n  // T is \"the point after one full turn\" for its radius, so its z is\n  // likewise the rise after one turn — z(θ) = cθ needs c per radian.\n  const risePerTurn = input.turn.z;\n  const c = risePerTurn / (2 * Math.PI);\n  const pitchAngleDeg = Math.acos(Math.abs(b) / Math.sqrt(1 + b * b)) * (180 / Math.PI);\n  return { a, b, c, growthRatio, risePerTurn, pitchAngleDeg };\n}"
  },
  "square-cube-law": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localSquareCubeLaw(point: Vec3): MagnitudeScalingResponse {\n  const radius = Math.max(Math.hypot(point.x, point.y, point.z), EPSILON);\n  const surfaceArea = 4 * Math.PI * radius * radius;\n  const volume = (4 / 3) * Math.PI * radius * radius * radius;\n  return { radius, surfaceArea, volume, ratio: surfaceArea / volume };\n}"
  },
  "catenary-arch": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function catenaryPoint(x: number, a: number): Vec3 {\n  return { x, y: a * (Math.cosh(x / a) - 1), z: 0 };\n}\n\nexport function localCatenary(aPoint: Vec3, halfSpan: number): CatenaryResponse {\n  const a = Math.max(Math.hypot(aPoint.x, aPoint.y), EPSILON);\n  const sag = a * (Math.cosh(halfSpan / a) - 1);\n  const arcLength = 2 * a * Math.sinh(halfSpan / a);\n  return { a, sag, arcLength };\n}"
  },
  "allometric-growth": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localAllometricGrowth(sizePoint: Vec3, exponentPoint: Vec3): AllometricGrowthResponse {\n  const x = Math.max(Math.hypot(sizePoint.x, sizePoint.y), EPSILON);\n  const k = Math.max(Math.hypot(exponentPoint.x, exponentPoint.y), EPSILON);\n  const y = Math.pow(x, k);\n  return { x, k, y, ratio: y / x };\n}"
  },
  "phyllotaxis": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function phyllotaxisPoint(index: number, divergenceRad: number, scale: number): Vec3 {\n  const theta = index * divergenceRad;\n  const r = scale * Math.sqrt(index);\n  return { x: r * Math.cos(theta), y: r * Math.sin(theta), z: 0 };\n}\n\nexport function localPhyllotaxis(divergencePoint: Vec3): PhyllotaxisResponse {\n  const rawAngle = Math.atan2(divergencePoint.y, divergencePoint.x);\n  const divergenceRad = rawAngle < 0 ? rawAngle + 2 * Math.PI : rawAngle;\n  const divergenceDeg = divergenceRad * (180 / Math.PI);\n  const goldenAngleDeg = GOLDEN_ANGLE_RAD * (180 / Math.PI);\n  return {\n    divergenceDeg,\n    goldenAngleDeg,\n    deviationDeg: Math.abs(divergenceDeg - goldenAngleDeg),\n  };\n}"
  },
  "logistic-growth": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function logisticPoint(t: number, r: number, k: number): Vec3 {\n  const n = k / (1 + Math.exp(r * (LOGISTIC_TIME_CENTER - t)));\n  return { x: t, y: n, z: 0 };\n}\n\nexport function localLogisticGrowth(rPoint: Vec3, kPoint: Vec3): LogisticGrowthResponse {\n  const r = Math.max(Math.hypot(rPoint.x, rPoint.y), EPSILON);\n  const k = Math.max(kPoint.y, EPSILON);\n  return {\n    r,\n    k,\n    inflectionTime: LOGISTIC_TIME_CENTER,\n    maxGrowthRate: (r * k) / 4,\n  };\n}"
  },
  "geodesic-sphere": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localGeodesicSphere(rawDetail: number): GeodesicSphereResponse {\n  const detail = Math.max(0, Math.min(6, Math.round(rawDetail)));\n  const f = detail + 1;\n  const vertices = 10 * f * f + 2;\n  const edges = 30 * f * f;\n  const faces = 20 * f * f;\n  return { detail, vertices, edges, faces, eulerCharacteristic: vertices - edges + faces };\n}"
  },
  "whirling-squares": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function buildWhirlingSquares(count: number): WhirlingSquare[] {\n  const directions: WhirlingSquare[\"direction\"][] = [\"left\", \"bottom\", \"right\", \"top\"];\n  let x0 = 0, y0 = 0, x1 = PHI, y1 = 1;\n  const squares: WhirlingSquare[] = [];\n  for (let i = 0; i < count; i++) {\n    const width = x1 - x0;\n    const height = y1 - y0;\n    const side = Math.min(width, height);\n    const direction = directions[i % 4];\n    let square: WhirlingSquare;\n    if (direction === \"left\") {\n      square = { x0, y0, x1: x0 + side, y1, direction };\n      x0 += side;\n    } else if (direction === \"bottom\") {\n      square = { x0, y0, x1, y1: y0 + side, direction };\n      y0 += side;\n    } else if (direction === \"right\") {\n      square = { x0: x1 - side, y0, x1, y1, direction };\n      x1 -= side;\n    } else {\n      square = { x0, y0: y1 - side, x1, y1, direction };\n      y1 -= side;\n    }\n    squares.push(square);\n  }\n  return squares;\n}\n\nexport function localWhirlingSquares(countPoint: Vec3): WhirlingSquaresResponse {\n  const count = Math.max(1, Math.min(14, Math.round(Math.max(Math.hypot(countPoint.x, countPoint.y), 1))));\n  // side_i = 1/φ^i (i = 0..count-1); each quarter-circle arc has length (π/2)·side_i.\n  let totalArcLength = 0;\n  for (let i = 0; i < count; i++) {\n    totalArcLength += (Math.PI / 2) * PHI ** -i;\n  }\n  return { count, ratio: PHI, totalArcLength };\n}"
  },
  "catenoid": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function catenoidRadius(z: number, a: number): number {\n  return a * Math.cosh(z / a);\n}\n\nexport function localCatenoid(aPoint: Vec3): CatenoidResponse {\n  const a = Math.max(Math.hypot(aPoint.x, aPoint.y), EPSILON);\n  const h = CATENOID_HALF_HEIGHT;\n  const rimRadius = catenoidRadius(h, a);\n  const bigH = h / a;\n  const surfaceArea = 2 * Math.PI * a * a * (bigH + Math.sinh(2 * bigH) / 2);\n  return { a, rimRadius, surfaceArea };\n}"
  },
  "milk-coronet": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function milkCoronetSpikeAngle(index: number, points: number): number {\n  return (2 * Math.PI * index) / points;\n}\n\nexport function localMilkCoronet(radiusPoint: Vec3, countPoint: Vec3): MilkCoronetResponse {\n  const radius = Math.max(Math.hypot(radiusPoint.x, radiusPoint.y), EPSILON);\n  const rawCount = Math.max(Math.hypot(countPoint.x, countPoint.y), MILK_CORONET_MIN_POINTS);\n  const points = Math.max(MILK_CORONET_MIN_POINTS, Math.min(MILK_CORONET_MAX_POINTS, Math.round(rawCount)));\n  const circumference = 2 * Math.PI * radius;\n  const chordLength = 2 * radius * Math.sin(Math.PI / points);\n  const polygonPerimeter = points * chordLength;\n  return {\n    radius,\n    points,\n    circumference,\n    polygonPerimeter,\n    circleDeficit: circumference - polygonPerimeter,\n  };\n}"
  },
  "egg-curve": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function localEggCurve(bigPoint: Vec3, smallPoint: Vec3): EggCurveResponse {\n  const bigRadius = clampEggRadius(Math.max(Math.hypot(bigPoint.x, bigPoint.y), EPSILON));\n  const smallRadius = clampEggRadius(Math.max(Math.hypot(smallPoint.x, smallPoint.y), EPSILON));\n  const d = EGG_CENTER_DISTANCE;\n  const alpha = Math.asin((bigRadius - smallRadius) / d);\n  const tangentLength = Math.sqrt(d * d - (bigRadius - smallRadius) * (bigRadius - smallRadius));\n  // The two tangent points sit at ±(π/2 + α) on EACH circle (parallel\n  // radii, the defining property of an external tangent). That splits\n  // each circle into a \"near\" arc (facing the other circle, cut away)\n  // and a \"far\" arc (kept, part of the outline) — but the far arc's\n  // angular width is NOT the same on both circles: it's (π − 2α) on the\n  // small circle (whose near arc, facing outward toward the bigger\n  // circle, is the wider one) and (π + 2α) on the big circle. The two\n  // widths sum to exactly 2π, one full circle's worth, only coinciding\n  // at π apiece when the radii are equal.\n  const smallArcAngle = Math.PI - 2 * alpha;\n  const bigArcAngle = Math.PI + 2 * alpha;\n  const perimeter = smallArcAngle * smallRadius + bigArcAngle * bigRadius + 2 * tangentLength;\n  // The surface area, unlike the perimeter, comes from each arc's AXIAL\n  // span (Archimedes' hat-box theorem: a spherical zone's area is\n  // 2π·radius·(its own height), independent of angular position), so it\n  // doesn't share the perimeter's angular bookkeeping.\n  const surfaceArea =\n    2 * Math.PI * bigRadius * bigRadius * (1 + Math.sin(alpha)) +\n    2 * Math.PI * smallRadius * smallRadius * (1 - Math.sin(alpha)) +\n    Math.PI * (bigRadius + smallRadius) * d * Math.cos(alpha) * Math.cos(alpha);\n  return {\n    bigRadius,\n    smallRadius,\n    tangentLength,\n    tiltAngleDeg: alpha * (180 / Math.PI),\n    perimeter,\n    surfaceArea,\n  };\n}"
  },
  "helicoid": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "export function helicoidPoint(u: number, v: number, c: number): Vec3 {\n  return { x: u * Math.cos(v), y: u * Math.sin(v), z: c * v };\n}\n\nexport function localHelicoid(radiusPoint: Vec3, pitchPoint: Vec3): HelicoidResponse {\n  const radius = Math.max(Math.hypot(radiusPoint.x, radiusPoint.y), EPSILON);\n  const risePerTurn = Math.max(Math.abs(pitchPoint.z), EPSILON);\n  const c = risePerTurn / (2 * Math.PI);\n  const totalAngle = HELICOID_TURNS * 2 * Math.PI;\n  const s = Math.sqrt(radius * radius + c * c);\n  const area = totalAngle * ((radius / 2) * s + (c * c / 2) * Math.log((radius + s) / c));\n  return { radius, c, risePerTurn, area };\n}"
  },
  "bee-cell": {
    "sourceLabel": "src/lib/local-geometry.ts",
    "code": "// Rim vertex `index` (0..5, 60° apart): even indices are \"kept\" (A-type,\n// z = 0), odd indices are \"trimmed\" (B-type, pushed down to z = -x).\nexport function beeCellRimVertex(index: number, x: number): Vec3 {\n  const angle = (Math.PI / 3) * index;\n  const isKept = index % 2 === 0;\n  return {\n    x: BEE_CELL_HEXAGON_SIDE * Math.cos(angle),\n    y: BEE_CELL_HEXAGON_SIDE * Math.sin(angle),\n    z: isKept ? 0 : -x,\n  };\n}\n\nexport function beeCellApex(x: number): Vec3 {\n  return { x: 0, y: 0, z: x };\n}\n\nexport function localBeeCell(risePoint: Vec3): BeeCellResponse {\n  const x = Math.max(BEE_CELL_MIN_RISE, Math.min(BEE_CELL_MAX_RISE, Math.hypot(risePoint.x, risePoint.y)));\n  const rhombusArea = beeCellRhombusArea(x);\n  const ridgeAngleDeg = Math.acos(x / Math.sqrt(1 + x * x)) * (180 / Math.PI);\n  const wallHeight = BEE_CELL_WALL_HEIGHT;\n  // 3 full-height \"kept\" walls + 3 shortened \"trimmed\" walls + 3 rhombi.\n  const totalSurfaceArea = 3 * wallHeight + 3 * (wallHeight - x) + 3 * rhombusArea;\n  const optimalX = BEE_CELL_OPTIMAL_RISE;\n  const optimalRidgeAngleDeg = Math.acos(optimalX / Math.sqrt(1 + optimalX * optimalX)) * (180 / Math.PI);\n  return { x, ridgeAngleDeg, rhombusArea, totalSurfaceArea, optimalX, optimalRidgeAngleDeg };\n}"
  }
};
