export type GlossaryEntry = { term: string; definition: string };

// Terms used across the app's chapters that a student might hit cold —
// plain-English definitions, not textbook-formal ones.
export const GLOSSARY: GlossaryEntry[] = [
  { term: "Acute angle", definition: "An angle measuring less than 90°." },
  { term: "Adjacent side", definition: "In a right triangle, the leg next to a chosen angle (not the hypotenuse, not the opposite side)." },
  { term: "Allometry", definition: "The study of how the size of one part of an organism relates to the size of the whole as it grows — described by y = xᵏ." },
  { term: "Arc length", definition: "The distance along a curved part (an arc) of a circle's edge." },
  { term: "Axis-aligned bounding box (AABB)", definition: "A box whose faces are all parallel to the x, y, and z axes — the simplest shape to test a ray or point against." },
  { term: "Catenary", definition: "The exact curve a chain or cable forms when it hangs freely under its own weight: y = a·cosh(x/a)." },
  { term: "Central angle", definition: "An angle whose vertex sits at a circle's center, cutting out an arc and a pie-slice sector." },
  { term: "Circumradius", definition: "The radius of the circle that passes through every vertex of a polygon." },
  { term: "Complementary angles", definition: "Two angles that add up to exactly 90°." },
  { term: "Congruent", definition: "Exactly the same size and shape — one could be placed directly on top of the other." },
  { term: "Coplanar", definition: "Lying on the same flat plane." },
  { term: "Cone frustum", definition: "The band-shaped piece left when the pointed tip is sliced off a cone." },
  { term: "Divergence angle", definition: "The fixed angle, seed to seed, that a plant rotates by as it produces each new seed or leaf around a growing tip." },
  { term: "Equiangular (logarithmic) spiral", definition: "A spiral that crosses every radius line at exactly the same angle — the curve shells and horns trace as they grow." },
  { term: "Euler's formula (for meshes)", definition: "For any sphere-like mesh, Vertices − Edges + Faces = 2, no matter how it's subdivided — a topological fact, not a coincidence of one shape." },
  { term: "Geodesic", definition: "The shortest path between two points on a curved surface — the surface's equivalent of a straight line." },
  { term: "Golden angle", definition: "≈137.5°, the angle that divides a circle in the golden ratio — the one angle no simple fraction approximates well, used in phyllotaxis." },
  { term: "Golden ratio (φ)", definition: "(1+√5)/2 ≈ 1.618 — the ratio at which a rectangle can have a square removed and leave a smaller copy of itself." },
  { term: "Homothety / dilation", definition: "A transformation that scales every point outward (or inward) from a fixed center by the same factor." },
  { term: "Hypotenuse", definition: "The longest side of a right triangle, opposite the right angle." },
  { term: "Interior angle", definition: "The angle inside a polygon at one of its vertices, between its two adjacent sides." },
  { term: "Isometric surfaces", definition: "Two surfaces that can be bent into each other without stretching or tearing — they share the same intrinsic geometry despite looking different in 3D (like the catenoid and helicoid)." },
  { term: "Isoperimetric quotient", definition: "A shape's efficiency score, 4πA/P² — exactly 1 for a circle (the most area for a given perimeter) and less than 1 for everything else." },
  { term: "Minimal surface", definition: "A surface that locally has the least possible area for its boundary — the shape a soap film naturally settles into." },
  { term: "Normal (vector)", definition: "A vector that points exactly perpendicular to a surface or plane." },
  { term: "Obtuse angle", definition: "An angle measuring more than 90° but less than 180°." },
  { term: "Opposite side", definition: "In a right triangle, the leg across from a chosen angle (not the hypotenuse, not the adjacent side)." },
  { term: "Reflex angle", definition: "An angle measuring more than 180° but less than 360°." },
  { term: "Rhombus", definition: "A quadrilateral with all four sides equal in length (a square is a special case)." },
  { term: "Similarity transformation", definition: "A combination of translation, rotation, and uniform scaling — it can move and resize a shape, but never changes any of its angles." },
  { term: "Spherical zone", definition: "The curved band left when a sphere is sliced by two parallel planes — its area is exactly 2π·(sphere radius)·(band height), no matter where the band sits (Archimedes' hat-box theorem)." },
  { term: "Straight angle", definition: "An angle of exactly 180° — two rays pointing in opposite directions." },
  { term: "Supplementary angles", definition: "Two angles that add up to exactly 180°." },
];
